name: 'Get & cache Dependencies'
description: 'get the dependencies'
runs:
  using: 'composite'
  steps: 
    - name: Cache depencencies
      id: cache
      uses: action/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash